export const JOBS_LIST_REQUEST = "JOBS_LIST_REQUEST";
export const JOBS_LIST_SUCCESS = "JOBS_LIST_SUCCESS";
export const JOBS_LIST_FAIL = "JOBS_LIST_FAIL";

export const JOBS_CREATE_REQUEST = "JOBS_CREATE_REQUEST";
export const JOBS_CREATE_SUCCESS = "JOBS_CREATE_SUCCESS";
export const JOBS_CREATE_FAIL = "JOBS_CREATE_FAIL";
export const JOBS_CREATE_RESET = "JOBS_CREATE_RESET";

export const JOB_MY_REQUEST = "JOB_MY_REQUEST";
export const JOB_MY_SUCCESS = "JOB_MY_SUCCESS";
export const JOB_MY_FAIL = "JOB_MY_FAIL";

export const JOBS_UPDATE_REQUEST = "JOBS_UPDATE_REQUEST";
export const JOBS_UPDATE_SUCCESS = "JOBS_UPDATE_SUCCESS";
export const JOBS_UPDATE_FAIL = "JOBS_UPDATE_FAIL";
export const JOBS_UPDATE_RESET = "JOBS_UPDATE_RESET";

export const JOBS_DELETE_REQUEST = "JOBS_DELETE_REQUEST";
export const JOBS_DELETE_SUCCESS = "JOBS_DELETE_SUCCESS";
export const JOBS_DELETE_FAIL = "JOBS_DELETE_FAIL";
export const JOBS_DELETE_RESET = "JOBS_DELETE_RESET";
