export const JOBS_LIST_REQUEST = "JOBS_LIST_REQUEST";
export const JOBS_LIST_SUCCESS = "JOBS_LIST_SUCCESS";
export const JOBS_LIST_FAIL = "JOBS_LIST_FAIL";

export const JOBS_CREATE_REQUEST = "JOBS_CREATE_REQUEST";
export const JOBS_CREATE_SUCCESS = "JOBS_CREATE_SUCCESS";
export const JOBS_CREATE_FAIL = "JOBS_CREATE_FAIL";
export const JOBS_CREATE_RESET = "JOBS_CREATE_RESET";
