export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_LIKE_SUCCESS = "PRODUCT_LIST_LIKE_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";
export const PRODUCT_DELETE_RESET = "PRODUCT_DELETE_RESET";

export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_FAIL = "PRODUCT_CREATE_FAIL";
export const PRODUCT_CREATE_RESET = "PRODUCT_CREATE_RESET";

export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAIL = "PRODUCT_UPDATE_FAIL";
export const PRODUCT_UPDATE_RESET = "PRODUCT_UPDATE_RESET";

export const PRODUCT_CREATE_LIKE_REQUEST = "PRODUCT_CREATE_LIKE_REQUEST";
export const PRODUCT_CREATE_LIKE_SUCCESS = "PRODUCT_CREATE_LIKE_SUCCESS";
export const PRODUCT_UPDATE_AFTER_LIKE = "PRODUCT_UPDATE_AFTER_LIKE";

export const PRODUCT_CREATE_LIKE_FAIL = "PRODUCT_CREATE_LIKE_FAIL";
export const PRODUCT_CREATE_LIKE_RESET = "PRODUCT_CREATE_LIKE_RESET";

export const PRODUCT_CREATE_COMMENT_REQUEST = "PRODUCT_CREATE_COMMENT_REQUEST";
export const PRODUCT_CREATE_COMMENT_SUCCESS = "PRODUCT_CREATE_COMMENT_SUCCESS";
export const PRODUCT_CREATE_COMMENT_FAIL = "PRODUCT_CREATE_COMMENT_FAIL";
export const PRODUCT_CREATE_COMMENT_RESET = "PRODUCT_CREATE_COMMENT_RESET";

export const PRODUCT_GET_LIKE_REQUEST = "PRODUCT_GET_LIKE_REQUEST";
export const PRODUCT_GET_LIKE_SUCCESS = "PRODUCT_GET_LIKE_SUCCESS";
export const PRODUCT_GET_LIKE_FAIL = "PRODUCT_GET_LIKE_FAIL";

export const PRODUCT_TOP_REQUEST = "PRODUCT_TOP_REQUEST";
export const PRODUCT_TOP_SUCCESS = "PRODUCT_TOP_SUCCESS";
export const PRODUCT_TOP_FAIL = "PRODUCT_TOP_FAIL";

export const PRODUCT_MY_REQUEST = "PRODUCT_MY_REQUEST";
export const PRODUCT_MY_SUCCESS = "PRODUCT_MY_SUCCESS";
export const PRODUCT_MY_FAIL = "PRODUCT_MY_FAIL";

export const PRODUCT_UPCOMING_REQUEST = "PRODUCT_UPCOMING_REQUEST";
export const PRODUCT_UPCOMING_SUCCESS = "PRODUCT_UPCOMING_SUCCESS";
export const PRODUCT_UPCOMING_FAIL = "PRODUCT_UPCOMING_FAIL";
export const PRODUCT_UPCOMING_LIKE_SUCCESS = "PRODUCT_UPCOMING_LIKE_SUCCESS";
